### ISSUE TITLE
Youtube block IP

### ISSUE THREAD

**Issue by mzhou52** [hangzhaomit/HACS-dataset#15]
Hello, We are ready to use your HACS dataset to do fMRI research. We have completely followed your instructions in README and used official script to download videos in youtube. However, as some people have reflected before, our IP is blocked due to crawling too many videos, which seems like the youtube has upgraded anti-web crawling measures. We check the youtube-dl and it's the latest version. 
You have mentioned that submitting a request with user agreement. Does it mean we need to finish the google form "HACS Video Request"? In that way, we need to supply almost the whole dataset as the missing video, and it is not allowed as the missing.txt is too large. We sincerely hope that there will be a reliable solution and use your dataset to do some research. Thanks for your help!

**Comment by hangzhaomit** [comment]
@Blink621 Yes please fill the Google form to request those videos. If one text file is too big to upload, please split it into mulitple ones. Thanks!

**Comment by mzhou52** [comment]
OK, we have filled the google form as required and hope we can get the links soon.  Thanks for your help!
