### ISSUE TITLE
httperror 429

### ISSUE THREAD

**Issue by Wells-WeiWei** [hangzhaomit/HACS-dataset#6]
Sometimes it appears httperror 429, it seem like the youtube has upgraded anti-web crawling measures and our IPs have been banned. We have use the latest version of youtube-dl. We can just download about 2000 videos at most, that means we can't use your website to download missing videos which are too much.

**Comment by hangzhaomit** [comment]
Alternatively you can submit a request with user agreement. Thanks!

**Comment by hangzhaomit** [comment]
Please also check out the instructions on youtube-dl
https://github.com/ytdl-org/youtube-dl

**Comment by bryanyzhu** [comment]
@Wells-WeiWei Did you solve the 429 error? I confirmed my youtube-dl version is the latest, 9.12.2019 version. But I still see lots of 429 error. I can only download hundreds of videos.

**Comment by hangzhaomit** [comment]
This now seems a common issue. Please submit a request with user agreement.
