### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by dreamedrainbow** [hangzhaomit/HACS-dataset#7]
Hello there. I completely follow your instructions in README. But I run into a problem. I want to know if your method is to crawl video from youtube one by one according to the video ID.If so, what can i do when my IP is blocked due to crawling too many videos?

**Comment by hangzhaomit** [comment]
Please make sure that you have the latest version of youtube-dl, also check out their page for FAQ
https://github.com/ytdl-org/youtube-dl

**Comment by dreamedrainbow** [comment]
Sorry to disturb you again. Let me talk about the problem I encountered in detail.
Here is my error:
![image](https://user-images.githubusercontent.com/32841250/64325303-76001000-cffa-11e9-899e-a88ff5ea13d1.png)
And my youtube-dl has upgraded to the latest version already,
![image](https://user-images.githubusercontent.com/32841250/64325096-1c97e100-cffa-11e9-9f1a-c07f092f1316.png)
What should I do next?
I use the proxy to download the dataset in WIN, by the way.

**Comment by dreamedrainbow** [comment]
> Please make sure that you have the latest version of youtube-dl, also check out their page for FAQ
> https://github.com/ytdl-org/youtube-dl
Sorry to disturb you again. Let me talk about the problem I encountered in detail.
Here is my error:
![image](https://user-images.githubusercontent.com/32841250/64325303-76001000-cffa-11e9-899e-a88ff5ea13d1.png)
And my youtube-dl has upgraded to the latest version already,
![image](https://user-images.githubusercontent.com/32841250/64325096-1c97e100-cffa-11e9-9f1a-c07f092f1316.png)
What should I do next?
I use the proxy to download the dataset in WIN, by the way.

**Comment by hangzhaomit** [comment]
I cannot help on youtube-dl unfortunately.
Alternatively you can submit a request to us with user agreement. Thanks!

**Comment by dreamedrainbow** [comment]
> I cannot help on youtube-dl unfortunately.
> Alternatively you can submit a request to us with user agreement. Thanks!
Do you mean the dataset download protocol? I did not find the relevant file in your website or profile，so I email you a protocol used in other match. If don't meet the requirements, please let me know, Thanks for your help!

**Comment by dreamedrainbow** [comment]
Dear Hang Zhao，
        I am the studet in github named hao zhang. I'd like to request the HACS segments for research only and the user agreement is placed in the attachment. If the file don't meet your requirements, please let me know. Thanks for your help!
Hao Zhang
2019.9.9
------------------ 原始邮件 ------------------
发件人: "Hang Zhao"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 下午3:49
收件人: "hangzhaomit/HACS-dataset"<HACS-dataset@noreply.github.com>;
抄送: "雨落烂漫"<32668646@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hangzhaomit/HACS-dataset] Download Error (#7)




I cannot help on youtube-dl unfortunately.
 Alternatively you can submit a request to us with user agreement. Thanks!

**Comment by hangzhaomit** [comment]
@dreamedrainbow Can you follow the instruction in this repo to submit a list of missing files? We have an automatic pipeline to share videos with you.
