### ISSUE TITLE
Same class label or multiple class labels for segment dataset?

### ISSUE THREAD

**Issue by bryanyzhu** [hangzhaomit/HACS-dataset#8]
Hi, thank you for hosting the great dataset. I have a quick question about the segment dataset. 

I understand that there are multiple action segments in one video, but do all the segments belong to one class or multiple classes? I glanced through the `.json` file, it seems to me that all the segments in one video will have the same class label. Thank you.

**Comment by hangzhaomit** [comment]
Hi @bryanyzhu , this not necessarily true. There are a few exceptions.

**Comment by bryanyzhu** [comment]
Got it, thank you for your reply. I will check into this dataset a bit more.
