### ISSUE TITLE
video damaged

### ISSUE THREAD

**Issue by jcaha** [hangzhaomit/HACS-dataset#9]
Thank you for your attention.
I have downloaded all of segments videos. When I was extracting frames from them, six videos among them seemed to be damaged, while there is no problem with the other videos. So I sumbitted a missing.txt for re-downloading the six videos:
![_W41M 1JF$GE6P3F 4)AL J](https://user-images.githubusercontent.com/18487284/65659076-c77d4700-e05c-11e9-8c65-09c9a4f8d8ed.png)

the video ids are v_2wE42p2P85g, v_EKhVsJ3rtyM, v_PXS1LtrnQXI, v_qh0kaLdrzJU, v_VubOnSthyKQ, v_Wj40pGUd368.
the newly downloaded ones encounter the same problem. When I try to extract frames from these videos, I see this:
![3)Y8ZGQ1M`}4J32E8CSH $S](https://user-images.githubusercontent.com/18487284/65659939-b41fab00-e05f-11e9-83aa-78ca0d7143fb.png)

And if I try to watch this video, I see this:
![P9@N(DMC909QKB}`G`1S DI](https://user-images.githubusercontent.com/18487284/65659624-dbc24380-e05e-11e9-8425-27a7c8acb47d.png)

the popup means that "This file cannot be played. This may be due to unsupported file types, incorrect file extensions, or corrupted files."
Could you have any advice for me? thank you very much.

**Comment by hangzhaomit** [comment]
Unfortunately, we are not able to access these videos either. We will remove them from our dataset. Sorry for the trouble.

**Comment by Scipio1996** [comment]
> the video ids are v_2wE42p2P85g, v_EKhVsJ3rtyM, v_PXS1LtrnQXI, v_qh0kaLdrzJU, v_VubOnSthyKQ, v_Wj40pGUd368.

Hi，I try to download the dataset,but it always http error:429. can you share the dataset with me ?Thanks!

**Comment by hangzhaomit** [comment]
It seems that Youtube blocked youtube-dl. Please submit a request with user agreement.
